// src/utiles/config/defaultFormTemplate.js
export const defaultFormTemplate = {
  fields: [
    {
      key: "orgId",
      label: "Client",
      placeholder: "Select client",
      field_type: "creation",
      type: "clientSelector",
      collection: "organization",
      input_modes: {
        dropdown: true,
        qr: true,
      },
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "string",
        required: true,
        message: "Client selection is required",
      },
    },
    {
      key: "UsersId",
      label: "Technician",
      placeholder: "Select employee",
      field_type: "creation",
      type: "dropdown",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "string",
        required: true,
        message: "Technician selection is required",
      },
    },
    {
      key: "from",
      label: "Service Start",
      placeholder: "Start date",
      field_type: "creation",
      type: { date: true },
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        required: true,
        allowPastDates: true,
        message:
          "Start date must be selected and should be at least 4 days before today",
      },
    },
    {
      key: "dueTime",
      label: "Service End",
      placeholder: "End date",
      field_type: "creation",
      type: { date: true },
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        required: true,
        mustBeAfterField: "from",
        message: "End date must be after the start date and within 3 days",
      },
    },
    {
      key: "user_location",
      label: "Technician GPS",
      type: "gps-currentLocation",
      field_type: "completion",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "location",
        required: true,
        message: "Technician location is required",
      },
    },
    {
      key: "client_location",
      label: "Client Location",
      type: "gps",
      field_type: "creation",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "location",
        required: true,
        message: "Client location is required",
      },
    },
    {
      key: "snNumber",
      label: "Device Serial Number",
      type: "text",
      field_type: "completion",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "string",
        minLength: 4,
        maxLength: 10,
        required: true,
        message: "Serial number must be between 4 and 10 characters",
      },
    },
    {
      key: "issueReport",
      label: "Reported Issue",
      type: "bigtext",
      field_type: "completion",
      placeholder: "Describe issue",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "string",
        required: true,
        maxLength: 300,
        minLength: 20,
        message: "Issue description must be between 20 and 300 characters",
      },
    },
    {
      key: "taskimage",
      label: "Upload Device Image",
      type: "image",
      field_type: "completion",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "image",
        required: true,
        maxSizeMB: 5,
        fileTypeAllowed: ["jpg", "jpeg", "png"],
        message: "Image must be JPG, JPEG, or PNG and under 5MB",
      },
    },
    {
      key: "description",
      label: "Service Details",
      type: "bigtext",
      field_type: "completion",
      placeholder: "What was serviced/fixed",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        type: "string",
        required: true,
        maxLength: 300,
        minLength: 20,
        message: "Service description must be between 20 and 300 characters",
      },
    },
    // {
    //   key: "otp",
    //   label: "New otp",
    //   placeholder: "Enter otp",
    //   field_type: "completion",
    //   type: "otp",
    //   roleBasedRequired: { Admin: true, Employee: true },
    //   roleBasedMandatory: { Admin: true, Employee: true },
    //   validations: {
    //     required: true,
    //     message: "OTP is required and must be 6 digits",
    //     length: 6,
    //   },
    // },
    {
      key: "happy_code",
      label: "New happy code",
      placeholder: "Enter happy code",
      field_type: "completion",
      type: "happy-code",
      roleBasedRequired: { Admin: true, Employee: true },
      roleBasedMandatory: { Admin: true, Employee: true },
      validations: {
        required: true,
        message: "Happy code is required and must be 6 digits",
        length: 6,
      },
    },
  ],
  form_visibility_to: {
    roles: ["Admin", "Employee"],
  },
  status_transitions: {
    "closed-overDue": {
      enabled: true,
      max_days_allowed: 4,
      can_set_by_roles: ["Admin"],
    },
  },
};
