org.gradle.jvmargs=-Xmx1536M -XX:MaxMetaspaceSize=384M -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx384M
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.caching=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false





